"""Tool registry: what the model can call, how risky it is, what it needs, and which worker runs it.

Tiers: R = read · WS = write to self · WO = write to others / public (approval) · D = destructive (approval).
Handlers are `async def handler(ctx, args) -> str | dict`. They raise ToolError for problems the model should see.
Heavy modules (Gmail, browser, Temporal) are imported inside handlers so every worker can load this registry.
"""

from collections.abc import Awaitable, Callable
from dataclasses import dataclass, field

from app import db


class ToolError(Exception):
    """A problem the model should be told about (becomes an error tool result, not a crash)."""


@dataclass(frozen=True)
class ToolCtx:
    turn_id: str
    tool_call_id: str


@dataclass(frozen=True)
class Tool:
    name: str
    description: str
    properties: dict
    required: tuple[str, ...]
    handler: Callable[[ToolCtx, dict], Awaitable[str | dict]]
    tier: str | Callable[[dict], str] = "R"
    needs: str | None = None          # e.g. "gmail.readonly", "gmail.send"
    queue: str = "agent"
    render: Callable[[dict], str] | None = None   # approval text, generated by code from the input
    limit_key: Callable[[dict], str] | None = None  # which rate-limit bucket a call counts against
    extra: dict = field(default_factory=dict)

    @property
    def schema(self) -> dict:
        return {"type": "object", "properties": self.properties, "required": list(self.required),
                "additionalProperties": False}

    def tier_for(self, args: dict) -> str:
        return self.tier(args) if callable(self.tier) else self.tier


TOOLS: dict[str, Tool] = {}


def tool(name, description, properties, required=(), **kw):
    def register(fn):
        TOOLS[name] = Tool(name, description, properties, tuple(required), fn, **kw)
        return fn
    return register


def definitions(names: list[str]) -> list[dict]:
    """The `tools` array for the model (OpenAI function format), in the given (sorted) order."""
    return [{"type": "function", "function": {"name": n, "description": TOOLS[n].description,
                                              "parameters": TOOLS[n].schema}} for n in names]


GMAIL_SCOPE = "https://www.googleapis.com/auth/"


def need_met(need: str | None, connections: dict[str, dict]) -> bool:
    if need is None:
        return True
    if need.startswith("gmail."):
        g = connections.get("google")
        return bool(g and g["status"] == "connected" and GMAIL_SCOPE + need in g["scopes"])
    return False


def menu_for(connections: dict[str, dict]) -> list[str]:
    """Tool names usable right now, sorted so the list is byte-stable between turns."""
    return sorted(n for n, t in TOOLS.items() if need_met(t.needs, connections))


async def load_connections() -> dict[str, dict]:
    rows = await db.fetchall("SELECT provider, status, scopes, meta FROM connections")
    return {r["provider"]: r for r in rows}


# ---------------------------------------------------------------- core tools

@tool("react_to_message", "React to the user's latest message with one emoji, e.g. 👀 when a task will take a while.",
      {"emoji": {"type": "string", "description": "A single emoji, e.g. 👀 👍 ❤️ 🔥 👌"}}, ["emoji"], tier="WS")
async def react_to_message(ctx: ToolCtx, args: dict) -> str:
    from app import telegram
    row = await db.fetchone(
        "SELECT tg_message_id FROM messages WHERE direction = 'in' AND kind = 'text' ORDER BY id DESC LIMIT 1")
    if not row:
        raise ToolError("no message to react to")
    try:
        await telegram.set_reaction(row["tg_message_id"], args["emoji"])
    except telegram.Permanent as e:
        raise ToolError(f"Telegram refused that reaction (use a common emoji): {e}") from e
    return "reacted"


# ---------------------------------------------------------------- memory (T-15, T-16)

@tool("remember_fact",
      "Save a durable personal fact the user told you (a preference, a person, a place, a routine) so you remember "
      "it in future conversations. Not for small talk or one-off details.",
      {"kind": {"type": "string", "enum": ["preference", "person", "place", "other"]},
       "content": {"type": "string", "maxLength": 300, "description": "The fact, short and self-contained"}},
      ["kind", "content"], tier="WS")
async def remember_fact(ctx: ToolCtx, args: dict) -> dict:
    content = " ".join(args["content"].split())
    if not content:
        raise ToolError("empty fact")
    src = await db.fetchone("SELECT id FROM messages WHERE direction = 'in' ORDER BY id DESC LIMIT 1")
    row = await db.fetchone(
        "INSERT INTO memory_facts (kind, content, source_message_id) VALUES (%s, %s, %s)"
        " ON CONFLICT (lower(btrim(content))) DO UPDATE SET updated_at = now(), kind = EXCLUDED.kind RETURNING id",
        (args["kind"], content, src["id"] if src else None))
    return {"saved": f"f{row['id']}"}


@tool("forget_fact", "Delete a remembered fact by its id (shown as [f12] in <facts>), when the user asks or it's wrong.",
      {"fact_id": {"type": "string", "pattern": "^f?[0-9]+$", "description": "e.g. f12"}}, ["fact_id"], tier="WS")
async def forget_fact(ctx: ToolCtx, args: dict) -> str:
    n = await db.execute("DELETE FROM memory_facts WHERE id = %s", (int(args["fact_id"].lstrip("f")),))
    if not n:
        raise ToolError(f"no fact {args['fact_id']}")
    return "forgotten"


@tool("search_history",
      "Search older conversations and remembered facts by keywords, when the user refers to something from the past "
      "that isn't in <recent_messages>. Use distinctive words (names, places, things).",
      {"query": {"type": "string", "minLength": 1}, "limit": {"type": "integer", "minimum": 1, "maximum": 10}},
      ["query"])
async def search_history(ctx: ToolCtx, args: dict) -> dict:
    from app.config import get_settings
    tz = get_settings().owner_timezone
    q, limit = args["query"], args.get("limit", 8)
    # OR the words together: a short keyword query should match messages with any of them, ranked by relevance.
    words = [w for w in q.replace('"', " ").split() if w.lower() not in {"or", "and", "the", "a"}]
    tsq = " OR ".join(words) or q
    rows = await db.fetchall(
        "SELECT * FROM ("
        " SELECT 'message' AS src, direction, sent_at AS at, body AS text,"
        "  ts_rank(tsv, websearch_to_tsquery('simple', %(q)s)) AS rank FROM messages"
        "  WHERE kind = 'text' AND tsv @@ websearch_to_tsquery('simple', %(q)s)"
        " UNION ALL"
        " SELECT 'fact', 'fact', updated_at, content, ts_rank(tsv, websearch_to_tsquery('simple', %(q)s)) + 1"
        "  FROM memory_facts WHERE tsv @@ websearch_to_tsquery('simple', %(q)s)"
        ") hits ORDER BY rank DESC, at DESC LIMIT %(n)s", {"q": tsq, "n": limit})
    if not rows:
        return {"results": [], "note": "nothing found; try other keywords"}
    who = {"in": "User", "out": "You", "fact": "Fact"}
    return {"results": [f"[{r['at'].astimezone(tz):%Y-%m-%d %H:%M}] {who[r['direction']]}: {r['text'][:400]}" for r in rows]}


# ---------------------------------------------------------------- Gmail (T-21, T-22)

@tool("search_email",
      "Search the user's Gmail. Supports Gmail search syntax, e.g. 'is:unread newer_than:2d', 'from:amazon', "
      "'subject:invoice after:2026/09/01'. Returns sender, subject, date and a snippet for each match.",
      {"query": {"type": "string"}, "max": {"type": "integer", "minimum": 1, "maximum": 10}},
      ["query"], needs="gmail.readonly")
async def search_email(ctx: ToolCtx, args: dict) -> str:
    from app import google
    found = await google.search_email(args["query"], args.get("max", 5))
    return google.wrap("gmail", found) if found else "no emails matched"


@tool("read_email", "Read one email's full text by its id (from search_email).",
      {"message_id": {"type": "string"}}, ["message_id"], needs="gmail.readonly")
async def read_email(ctx: ToolCtx, args: dict) -> str:
    from app import google
    return google.wrap("gmail", await google.read_email(args["message_id"]))


def _render_email(a: dict) -> str:
    head = f"Send email to {', '.join(a['to'])}\nSubject: {a['subject']}"
    if a.get("reply_to_message_id"):
        head += "\n(reply in the same thread)"
    return f"{head}\n---\n{a['body']}"


@tool("send_email",
      "Send an email from the user's Gmail, or reply in a thread (pass reply_to_message_id). The user must approve "
      "it with a button before it is sent; write the exact final text.",
      {"to": {"type": "array", "items": {"type": "string", "format": "email"}, "minItems": 1, "maxItems": 5},
       "subject": {"type": "string", "maxLength": 200},
       "body": {"type": "string", "maxLength": 5000},
       "reply_to_message_id": {"type": "string"}},
      ["to", "subject", "body"], tier="WO", needs="gmail.send", render=_render_email)
async def send_email(ctx: ToolCtx, args: dict) -> dict:
    from app import google
    return await google.send_email(args["to"], args["subject"], args["body"], args.get("reply_to_message_id"))


# ---------------------------------------------------------------- browser (T-29, T-30)

def _render_browser(a: dict) -> str:
    start = a.get("start_url") or "agent decides"
    return f"Do this in your browser:\n{a['goal']}\n(start: {start})"


@tool("browser_task",
      "Use the user's own browser to do something on ANY website. mode 'read' only looks (search, read, check); "
      "mode 'act' submits, posts, sends, buys or changes something and needs the user's approval. Give ONE clear goal, "
      "and a start_url if you know it. If a login, CAPTCHA or 2FA blocks it, the user is asked to take over.",
      {"goal": {"type": "string", "maxLength": 500},
       "mode": {"type": "string", "enum": ["read", "act"]},
       "start_url": {"type": "string", "pattern": "^https?://"}},
      ["goal", "mode"], tier=lambda a: "WO" if a["mode"] == "act" else "R", queue="browser",
      render=_render_browser, limit_key=lambda a: f"browser_task:{a['mode']}")
async def browser_task(ctx: ToolCtx, args: dict) -> dict:
    from app import browser, telegram
    from app.activities import TAKEOVER_TTL, request_approval
    from app.agent import guard
    from app.config import get_settings

    async def on_action(name, shown, result, url):
        await guard.audit("browser_action", "executed" if result == "ok" else "failed", turn_id=ctx.turn_id or None,
                          detail={"action": name, "args": shown, "result": result, "url": url[:300]})

    r = await browser.run_browser_task(args["goal"], args["mode"], args.get("start_url"), on_action=on_action)
    if r["status"] == "needs_user":
        await request_approval(ctx.turn_id or None, "takeover", args,
                               f"{r['reason']}.\nOpen your browser here: {get_settings().live_view_url}\n"
                               "Tap Done when you've finished.", ttl=TAKEOVER_TTL, kind="take")
        return {"status": "needs_user", "reason": r["reason"],
                "note": "The user was sent the live-view link and a Done button. Tell them briefly and wait."}
    if r["status"] == "failed":
        raise ToolError(f"browser task failed: {r['reason']}")
    if r.get("screenshot"):
        await telegram.send_photo(r["screenshot"], caption=args["goal"][:200], turn_id=ctx.turn_id or None)
    return {"status": "done", "result": untrusted_browser(r["summary"]), "user_text": r["summary"]}


def untrusted_browser(text: str) -> str:
    from app.agent.context import untrusted
    return untrusted("browser", text)


# ---------------------------------------------------------------- scheduled tasks (T-32..T-34), stored in Temporal

def _local(dt) -> str:
    from app.config import get_settings
    return dt.astimezone(get_settings().owner_timezone).strftime("%a %d %b %H:%M")


@tool("schedule_task",
      "Schedule something for later. kind 'remind' = send the user a reminder message with `text`. kind 'do' = at that "
      "time YOU perform `text` as an instruction (e.g. 'check Hacker News and send me the top 5'). Give fire_at (ISO 8601 "
      "with offset, one time) OR cron (5 fields, repeating, user's timezone, e.g. '0 9 * * MON').",
      {"kind": {"type": "string", "enum": ["remind", "do"]},
       "text": {"type": "string", "minLength": 1, "maxLength": 300},
       "fire_at": {"type": "string"},
       "cron": {"type": "string"}},
      ["kind", "text"], tier="WS")
async def schedule_task(ctx: ToolCtx, args: dict) -> str:
    import secrets
    from datetime import datetime, timedelta, timezone

    from temporalio.client import (Schedule, ScheduleActionStartWorkflow, ScheduleOverlapPolicy, SchedulePolicy,
                                   ScheduleSpec)

    from app.clients import temporal
    from app.config import get_settings
    from app.workflows import ScheduledTaskWorkflow, TaskFireWorkflow

    if bool(args.get("fire_at")) == bool(args.get("cron")):
        raise ToolError("give exactly one of fire_at (one time) or cron (repeating)")
    task_id = f"task-{secrets.token_hex(4)}"
    task = {"id": task_id, "kind": args["kind"], "text": args["text"]}
    client = await temporal()
    now = datetime.now(timezone.utc)

    if fire_at := args.get("fire_at"):
        try:
            when = datetime.fromisoformat(fire_at)
        except ValueError:
            raise ToolError("fire_at must be ISO 8601, e.g. 2026-10-03T08:00:00+05:30") from None
        if when.tzinfo is None:
            raise ToolError("fire_at needs a timezone offset, e.g. +05:30")
        if not now + timedelta(seconds=30) < when < now + timedelta(days=366):
            raise ToolError("fire_at must be at least 30 seconds and at most a year from now")
        task["fire_at"] = when.isoformat()
        await client.start_workflow(ScheduledTaskWorkflow.run, task, id=task_id, task_queue="agent",
                                    memo={"kind": task["kind"], "text": task["text"], "when": task["fire_at"]})
        return f"Scheduled [{task_id}] for {_local(when)}"

    cron = " ".join(args["cron"].split())
    if len(cron.split()) != 5:
        raise ToolError("cron needs exactly 5 fields: minute hour day-of-month month day-of-week")
    s = get_settings()
    try:
        handle = await client.create_schedule(
            task_id,
            Schedule(action=ScheduleActionStartWorkflow(TaskFireWorkflow.run, task, id=f"{task_id}-run", task_queue="agent"),
                     spec=ScheduleSpec(cron_expressions=[cron], time_zone_name=str(s.owner_timezone)),
                     policy=SchedulePolicy(overlap=ScheduleOverlapPolicy.SKIP, catchup_window=timedelta(hours=1))),
            memo={"kind": task["kind"], "text": task["text"], "when": cron})
    except Exception as e:
        raise ToolError(f"invalid cron {cron!r}: {e}") from e
    upcoming = (await handle.describe()).info.next_action_times[:2]
    min_gap = timedelta(minutes=s.recurring_do_min_minutes if args["kind"] == "do" else 1)
    if len(upcoming) == 2 and upcoming[1] - upcoming[0] < min_gap:
        await handle.delete()
        raise ToolError(f"repeating '{args['kind']}' tasks can run at most every {min_gap} (each 'do' run uses AI requests)")
    first = f", first at {_local(upcoming[0])}" if upcoming else ""
    return f"Scheduled [{task_id}] repeating '{cron}' ({s.owner_timezone}){first}"


@tool("list_tasks", "List scheduled tasks (one-time and repeating) and pending approvals.", {}, [])
async def list_tasks(ctx: ToolCtx, args: dict) -> dict:
    from datetime import datetime

    from app.clients import temporal
    client = await temporal()
    items = []
    async for wf in client.list_workflows('WorkflowType = "ScheduledTaskWorkflow" AND ExecutionStatus = "Running"'):
        m = await wf.memo()
        items.append(f"[{wf.id}] {m.get('kind')} · {_local(datetime.fromisoformat(m['when']))} · {m.get('text')!r}")
    async for sc in await client.list_schedules():
        m = await sc.memo()
        if sc.id.startswith("task-"):
            items.append(f"[{sc.id}] {m.get('kind')} · repeating '{m.get('when')}' · {m.get('text')!r}")
    rows = await db.fetchall("SELECT tool, summary FROM approvals WHERE status = 'pending' AND expires_at > now()")
    items += [f"waiting for your tap: {r['summary'].splitlines()[0]}" for r in rows]
    return {"tasks": items or ["nothing scheduled"]}


@tool("cancel_task", "Cancel a scheduled task by its id, e.g. task-1a2b3c4d.",
      {"task_id": {"type": "string", "pattern": "^task-[0-9a-f]{8}$"}}, ["task_id"], tier="WS")
async def cancel_task(ctx: ToolCtx, args: dict) -> str:
    from temporalio.service import RPCError

    from app.clients import temporal
    client = await temporal()
    try:
        await client.get_workflow_handle(args["task_id"]).cancel()
        return f"cancelled {args['task_id']}"
    except RPCError:
        pass
    try:
        await client.get_schedule_handle(args["task_id"]).delete()
        return f"cancelled repeating {args['task_id']}"
    except RPCError:
        return f"{args['task_id']} was already gone"
